INSERT INTO OWNER (id, FIRST_NAME, LAST_NAME, IMMATRICULATION_NUMBER)
VALUES (SEQ_OWNER.nextval, 'Fadi', 'Albadin', 'E7361211A');
INSERT INTO OWNER (id, FIRST_NAME, LAST_NAME, IMMATRICULATION_NUMBER)
VALUES (SEQ_OWNER.nextval, 'Tanguy', 'Ricaille', 'R3235643T');